#! /bin/bash

# install twurtle

chmod +x runtwurtle

# get and install minecraft and mcpi API

chmod +x runmc

wget https://s3.amazonaws.com/assets.minecraft.net/pi/minecraft-pi-0.1.1.tar.gz
mv minecraft-pi-0.1.1.tar.gz code/minecraft
pushd code/minecraft
tar -zxvf minecraft-pi-0.1.1.tar.gz
cp -r mcpi/api/python/mcpi/* mcpi
popd
